version: '3'

services:
  app:
    build: .
    container_name: micro-videos-app
    #    entrypoint: dockerize -template ./.docker/app/.env:./.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    #    environment:
    #      - DB_HOST=db
    #      - DB_PORT=3306
    #      - DB_DATABASE=laravel
    #      - DB_USERNAME=root
    #      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis


  nginx:
    build: .docker/nginx
    container_name: micro-videos-nginx
    restart: always
    tty: true
    #    command: /bin/bash -c "dockerize -template /etc/nginx/conf.d/nginx.tmpl:/etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'"
    ports:
      - "80:80"
    #    environment:
    #      - PHP_HOST=app
    #      - PHP_PORT=9000
    volumes:
      - .:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: micro-videos-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=code_micro_videos
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: micro-videos-redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
